# Generated by Django 4.1.5 on 2024-07-18 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_work', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
    ]
