# Generated by Django 4.1.5 on 2024-07-20 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_work', '0003_dailyworkmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalholidays',
            name='speciality',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
