# Generated by Django 4.1.5 on 2024-07-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_work', '0006_dailyupdatemodel_dailytaskmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytaskmodel',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
