# Generated by Django 4.1.5 on 2024-07-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_work', '0007_dailytaskmodel_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyupdatemodel',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
