# Generated by Django 4.1.5 on 2024-07-21 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_work', '0008_dailyupdatemodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyupdatemodel',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
