# Generated by Django 4.1.5 on 2024-08-04 22:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_work', '0010_leaveupdate_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(max_length=200)),
                ('transport', models.CharField(blank=True, choices=[('private_vehicle', 'private_vehicle'), ('public_transport', 'public_transport'), ('company_vehicle', 'company_vehicle'), ('others', 'others')], max_length=20, null=True)),
                ('ticket', models.FileField(blank=True, null=True, upload_to='poster/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'png'])])),
                ('fuel_receipt', models.FileField(blank=True, null=True, upload_to='poster/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'png'])])),
                ('food_bill', models.FileField(blank=True, null=True, upload_to='poster/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'png'])])),
                ('expense', models.PositiveBigIntegerField()),
                ('approve', models.BooleanField(default=False)),
                ('reject', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='DailyWorkModel',
        ),
    ]
