# Generated by Django 4.1.5 on 2024-08-05 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_work', '0011_expencemodel_delete_dailyworkmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='expencemodel',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
