# Generated by Django 4.1.5 on 2024-08-05 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_work', '0012_expencemodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='expencemodel',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
