# Generated by Django 4.1.5 on 2024-08-06 07:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_work', '0014_expencemodel_others'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expencemodel',
            name='food_bill',
            field=models.FileField(blank=True, null=True, upload_to='poster/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='expencemodel',
            name='fuel_receipt',
            field=models.FileField(blank=True, null=True, upload_to='poster/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='expencemodel',
            name='others',
            field=models.FileField(blank=True, null=True, upload_to='poster/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='expencemodel',
            name='ticket',
            field=models.FileField(blank=True, null=True, upload_to='poster/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='spouse_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
